dependencies:
- name: postgresql
  version: 0.9.5
  repository: file://local-charts/postgresql
  condition: postgresql.enabled
  tags:
  - db
- name: redis
  version: 1.2.2
  repository: file://local-charts/redis
  condition: redis.enabled
  tags:
  - queue
- name: result
  version: 1.1.1
  repository: file://local-charts/result
  tags:
  - node
- name: vote
  version: 1.1.1
  repository: file://local-charts/vote
  tags:
  - python
- name: worker
  version: 1.1.1
  repository: file://local-charts/worker
  tags:
  - dotnet